# Generated by Django 5.2.6 on 2025-09-28 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(default='', max_length=1023)),
                ('icon', models.ImageField(upload_to='campaign_icons')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dnd.campaign'),
        ),
        migrations.CreateModel(
            name='CampaignMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.player')),
            ],
        ),
        migrations.CreateModel(
            name='RoomParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.character')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.player')),
            ],
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
    ]
