# Generated by Django 5.2.6 on 2025-09-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0002_campaign_character_campaign_campaignmembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='verified',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
