# Generated by Django 5.2.6 on 2025-09-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0003_campaign_verified_player_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='private',
            field=models.BooleanField(default=0),
        ),
    ]
